"""Initial procurement schema"""
from alembic import op
import sqlalchemy as sa

revision = '2305dc836ec3'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('required_role', sa.String(length=30), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cost_center', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_category'), 'price_history', ['category'], unique=False)
    op.create_index(op.f('ix_price_history_item_name'), 'price_history', ['item_name'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('contact', sa.String(length=80), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supabase_user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('requester','procurement','approver','finance_admin')"),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('supabase_user_id')
    )
    op.create_table('vendor_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('completed_orders', sa.Integer(), nullable=False),
    sa.Column('late_deliveries', sa.Integer(), nullable=False),
    sa.Column('anomalous_lines', sa.Integer(), nullable=False),
    sa.Column('quotation_lines', sa.Integer(), nullable=False),
    sa.Column('disputed_orders', sa.Integer(), nullable=False),
    sa.Column('incomplete_orders', sa.Integer(), nullable=False),
    sa.Column('invoice_mismatches', sa.Integer(), nullable=False),
    sa.Column('invoiced_orders', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('justification', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('estimated_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('preferred_vendor_id', sa.Integer(), nullable=True),
    sa.Column('approval_plan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('DRAFT','SUBMITTED','SOURCING','QUOTATIONS_RECEIVED','COMPARISON_READY','PENDING_APPROVAL','APPROVED','REJECTED','PO_ISSUED','DELIVERED','INVOICED','CLOSED','CANCELLED')"),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['preferred_vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisitions_requester_id'), 'requisitions', ['requester_id'], unique=False)
    op.create_index(op.f('ix_requisitions_status'), 'requisitions', ['status'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('approval_level', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=2000), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisition_id', 'approval_level'),
    sa.UniqueConstraint('requisition_id', 'approver_id')
    )
    op.create_index(op.f('ix_approvals_requisition_id'), 'approvals', ['requisition_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('requisition_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_requisition_id'), 'audit_logs', ['requisition_id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('po_number', sa.String(length=60), nullable=False),
    sa.Column('total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number'),
    sa.UniqueConstraint('requisition_id')
    )
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('quotation_number', sa.String(length=80), nullable=False),
    sa.Column('quotation_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('delivery_terms', sa.String(length=500), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('tax_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discount_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisition_id', 'vendor_id')
    )
    op.create_index(op.f('ix_quotations_requisition_id'), 'quotations', ['requisition_id'], unique=False)
    op.create_index(op.f('ix_quotations_vendor_id'), 'quotations', ['vendor_id'], unique=False)
    op.create_table('requisition_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('estimated_unit_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('estimated_line_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.CheckConstraint('estimated_unit_price > 0'),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisition_items_requisition_id'), 'requisition_items', ['requisition_id'], unique=False)
    op.create_table('vendor_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('response_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisition_id', 'vendor_id')
    )
    op.create_index(op.f('ix_vendor_invitations_requisition_id'), 'vendor_invitations', ['requisition_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('delivered_at', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_purchase_order_id'), 'deliveries', ['purchase_order_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=80), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('mismatch_flag', sa.Boolean(), nullable=False),
    sa.Column('mismatch_reason', sa.String(length=500), nullable=False),
    sa.Column('resolution_comment', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_order_id')
    )
    op.create_table('quotation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('requisition_item_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('tax', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.CheckConstraint('quantity > 0'),
    sa.CheckConstraint('unit_price > 0'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['requisition_item_id'], ['requisition_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quotation_id', 'requisition_item_id')
    )
    op.create_index(op.f('ix_quotation_items_quotation_id'), 'quotation_items', ['quotation_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=200), nullable=False),
    sa.Column('backend', sa.String(length=20), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.String(length=180), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(quotation_id IS NULL) <> (invoice_id IS NULL)'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['requisitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id'),
    sa.UniqueConstraint('quotation_id')
    )
    op.create_index(op.f('ix_documents_requisition_id'), 'documents', ['requisition_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_requisition_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_quotation_items_quotation_id'), table_name='quotation_items')
    op.drop_table('quotation_items')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_deliveries_purchase_order_id'), table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_vendor_invitations_requisition_id'), table_name='vendor_invitations')
    op.drop_table('vendor_invitations')
    op.drop_index(op.f('ix_requisition_items_requisition_id'), table_name='requisition_items')
    op.drop_table('requisition_items')
    op.drop_index(op.f('ix_quotations_vendor_id'), table_name='quotations')
    op.drop_index(op.f('ix_quotations_requisition_id'), table_name='quotations')
    op.drop_table('quotations')
    op.drop_table('purchase_orders')
    op.drop_index(op.f('ix_audit_logs_requisition_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_approvals_requisition_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_requisitions_status'), table_name='requisitions')
    op.drop_index(op.f('ix_requisitions_requester_id'), table_name='requisitions')
    op.drop_table('requisitions')
    op.drop_table('vendor_history')
    op.drop_table('profiles')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_price_history_item_name'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_category'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('departments')
    op.drop_table('approval_rules')
    # ### end Alembic commands ###
